package com.tnt.entity;

// Generated 13 Jun, 2016 1:02:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Inrqpt01Id generated by hbm2java
 */
public class Inrqpt01Id implements java.io.Serializable {

	private String uuid;
	private String prdid;

	public Inrqpt01Id() {
	}

	public Inrqpt01Id(String uuid, String prdid) {
		this.uuid = uuid;
		this.prdid = prdid;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getPrdid() {
		return this.prdid;
	}

	public void setPrdid(String prdid) {
		this.prdid = prdid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Inrqpt01Id))
			return false;
		Inrqpt01Id castOther = (Inrqpt01Id) other;

		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null
				&& castOther.getUuid() != null && this.getUuid().equals(
				castOther.getUuid())))
				&& ((this.getPrdid() == castOther.getPrdid()) || (this
						.getPrdid() != null && castOther.getPrdid() != null && this
						.getPrdid().equals(castOther.getPrdid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result
				+ (getPrdid() == null ? 0 : this.getPrdid().hashCode());
		return result;
	}

}
