package com.tnt.entity;

// Generated 13 Jun, 2016 1:02:40 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inrqut01 generated by hbm2java
 */
public class Inrqut01 implements java.io.Serializable {

	private String uuid;
	private String pkgty;
	private String channel;
	private Date colTd;
	private BigDecimal tlwgt;
	private BigDecimal tlvol;
	private String uomvl;
	private String uomwt;
	private String uomln;
	private String lancd;
	private String coucd;
	private String currcd;
	private BigDecimal gdval;
	private BigInteger tlitms;
	private String paytrms;
	private String sysCd;
	private Long accNum;
	private String srct;
	private String srsd;
	private String srcoucd;
	private String srpc;
	private String toct;
	private String tosd;
	private String tocoucd;
	private String topc;
	private String isDeleted;
	private Date crtTd;
	private Date updtTd;
	/*private Set inrqpt01s = new HashSet(0);
	private Set inrqit01s = new HashSet(0);
	private Set inrqot01s = new HashSet(0);*/
	private Set<Inrqpt01> inrqpt01s  = new HashSet<Inrqpt01>();
	private Set<Inrqit01> inrqit01s = new HashSet<Inrqit01>();
	private Set<Inrqot01> inrqot01s =new HashSet<Inrqot01>() ;
	public Inrqut01() {
	}

	public Inrqut01(String uuid) {
		this.uuid = uuid;
	}

	public Inrqut01(String uuid, String pkgty, String channel, Date colTd,
			BigDecimal tlwgt, BigDecimal tlvol, String uomvl, String uomwt,
			String uomln, String lancd, String coucd, String currcd,
			BigDecimal gdval, BigInteger tlitms, String paytrms, String sysCd,
			Long accNum, String srct, String srsd, String srcoucd, String srpc,
			String toct, String tosd, String tocoucd, String topc,
			String isDeleted, Date crtTd, Date updtTd,
			Set inrqpt01s, Set inrqit01s, Set inrqot01s) {
		this.uuid = uuid;
		this.pkgty = pkgty;
		this.channel = channel;
		this.colTd = colTd;
		this.tlwgt = tlwgt;
		this.tlvol = tlvol;
		this.uomvl = uomvl;
		this.uomwt = uomwt;
		this.uomln = uomln;
		this.lancd = lancd;
		this.coucd = coucd;
		this.currcd = currcd;
		this.gdval = gdval;
		this.tlitms = tlitms;
		this.paytrms = paytrms;
		this.sysCd = sysCd;
		this.accNum = accNum;
		this.srct = srct;
		this.srsd = srsd;
		this.srcoucd = srcoucd;
		this.srpc = srpc;
		this.toct = toct;
		this.tosd = tosd;
		this.tocoucd = tocoucd;
		this.topc = topc;
		this.isDeleted = isDeleted;
		this.crtTd = crtTd;
		this.updtTd = updtTd;
		this.inrqpt01s = inrqpt01s;
		this.inrqit01s = inrqit01s;
		this.inrqot01s = inrqot01s;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getPkgty() {
		return this.pkgty;
	}

	public void setPkgty(String pkgty) {
		this.pkgty = pkgty;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Date getColTd() {
		return this.colTd;
	}

	public void setColTd(Date colTd) {
		this.colTd = colTd;
	}

	public BigDecimal getTlwgt() {
		return this.tlwgt;
	}

	public void setTlwgt(BigDecimal tlwgt) {
		this.tlwgt = tlwgt;
	}

	public BigDecimal getTlvol() {
		return this.tlvol;
	}

	public void setTlvol(BigDecimal tlvol) {
		this.tlvol = tlvol;
	}

	public String getUomvl() {
		return this.uomvl;
	}

	public void setUomvl(String uomvl) {
		this.uomvl = uomvl;
	}

	public String getUomwt() {
		return this.uomwt;
	}

	public void setUomwt(String uomwt) {
		this.uomwt = uomwt;
	}

	public String getUomln() {
		return this.uomln;
	}

	public void setUomln(String uomln) {
		this.uomln = uomln;
	}

	public String getLancd() {
		return this.lancd;
	}

	public void setLancd(String lancd) {
		this.lancd = lancd;
	}

	public String getCoucd() {
		return this.coucd;
	}

	public void setCoucd(String coucd) {
		this.coucd = coucd;
	}

	public String getCurrcd() {
		return this.currcd;
	}

	public void setCurrcd(String currcd) {
		this.currcd = currcd;
	}

	public BigDecimal getGdval() {
		return this.gdval;
	}

	public void setGdval(BigDecimal gdval) {
		this.gdval = gdval;
	}

	public BigInteger getTlitms() {
		return this.tlitms;
	}

	public void setTlitms(BigInteger tlitms) {
		this.tlitms = tlitms;
	}

	public String getPaytrms() {
		return this.paytrms;
	}

	public void setPaytrms(String paytrms) {
		this.paytrms = paytrms;
	}

	public String getSysCd() {
		return this.sysCd;
	}

	public void setSysCd(String sysCd) {
		this.sysCd = sysCd;
	}

	public Long getAccNum() {
		return this.accNum;
	}

	public void setAccNum(Long accNum) {
		this.accNum = accNum;
	}

	public String getSrct() {
		return this.srct;
	}

	public void setSrct(String srct) {
		this.srct = srct;
	}

	public String getSrsd() {
		return this.srsd;
	}

	public void setSrsd(String srsd) {
		this.srsd = srsd;
	}

	public String getSrcoucd() {
		return this.srcoucd;
	}

	public void setSrcoucd(String srcoucd) {
		this.srcoucd = srcoucd;
	}

	public String getSrpc() {
		return this.srpc;
	}

	public void setSrpc(String srpc) {
		this.srpc = srpc;
	}

	public String getToct() {
		return this.toct;
	}

	public void setToct(String toct) {
		this.toct = toct;
	}

	public String getTosd() {
		return this.tosd;
	}

	public void setTosd(String tosd) {
		this.tosd = tosd;
	}

	public String getTocoucd() {
		return this.tocoucd;
	}

	public void setTocoucd(String tocoucd) {
		this.tocoucd = tocoucd;
	}

	public String getTopc() {
		return this.topc;
	}

	public void setTopc(String topc) {
		this.topc = topc;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Serializable getCrtTd() {
		return this.crtTd;
	}

	public void setCrtTd(Date crtTd) {
		this.crtTd = crtTd;
	}

	public Date getUpdtTd() {
		return this.updtTd;
	}

	public void setUpdtTd(Date updtTd) {
		this.updtTd = updtTd;
	}

	public Set<Inrqpt01> getInrqpt01s() {
		return this.inrqpt01s;
	}

	public void setInrqpt01s(Set inrqpt01s) {
		this.inrqpt01s = inrqpt01s;
	}

	public Set<Inrqit01> getInrqit01s() {
		return this.inrqit01s;
	}

	public void setInrqit01s(Set<Inrqit01> inrqit01s) {
		this.inrqit01s = inrqit01s;
	}

	public Set getInrqot01s() {
		return this.inrqot01s;
	}

	public void setInrqot01s(Set inrqot01s) {
		this.inrqot01s = inrqot01s;
	}

}
