package com.tnt.entity;

// Generated 13 Jun, 2016 1:02:40 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Inrqot01 generated by hbm2java
 */
public class Inrqot01 implements java.io.Serializable {

	private Inrqot01Id id;
	private Inrqut01 inrqut01;
	private BigDecimal opprc;
	private BigDecimal tlprc;
	private String isDeleted;
	private Serializable crtTd;
	private Serializable updtTd;

	public Inrqot01() {
	}

	public Inrqot01(Inrqot01Id id, Inrqut01 inrqut01) {
		this.id = id;
		this.inrqut01 = inrqut01;
	}

	public Inrqot01(Inrqot01Id id, Inrqut01 inrqut01, BigDecimal opprc,
			BigDecimal tlprc, String isDeleted, Serializable crtTd,
			Serializable updtTd) {
		this.id = id;
		this.inrqut01 = inrqut01;
		this.opprc = opprc;
		this.tlprc = tlprc;
		this.isDeleted = isDeleted;
		this.crtTd = crtTd;
		this.updtTd = updtTd;
	}

	public Inrqot01Id getId() {
		return this.id;
	}

	public void setId(Inrqot01Id id) {
		this.id = id;
	}

	public Inrqut01 getInrqut01() {
		return this.inrqut01;
	}

	public void setInrqut01(Inrqut01 inrqut01) {
		this.inrqut01 = inrqut01;
	}

	public BigDecimal getOpprc() {
		return this.opprc;
	}

	public void setOpprc(BigDecimal opprc) {
		this.opprc = opprc;
	}

	public BigDecimal getTlprc() {
		return this.tlprc;
	}

	public void setTlprc(BigDecimal tlprc) {
		this.tlprc = tlprc;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Serializable getCrtTd() {
		return this.crtTd;
	}

	public void setCrtTd(Serializable crtTd) {
		this.crtTd = crtTd;
	}

	public Serializable getUpdtTd() {
		return this.updtTd;
	}

	public void setUpdtTd(Serializable updtTd) {
		this.updtTd = updtTd;
	}

}
