package com.tnt.entity;

// Generated 13 Jun, 2016 1:02:40 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Inrqpt01 generated by hbm2java
 */
public class Inrqpt01 implements java.io.Serializable {

	private Inrqpt01Id id;
	private Inrqut01 inrqut01;
	private String lob;
	private String pdgrp;
	private String pdsgp;
	private String prdty;
	private BigDecimal enhancedLiabilityValue;
	private String cusdr;
	private Long frmlocid;
	private Long tolocid;
	private String currcd;
	private BigDecimal price;
	private BigDecimal vat;
	private String isDeleted;
	private Serializable crtTd;
	private Serializable updtTd;

	public Inrqpt01() {
	}

	public Inrqpt01(Inrqpt01Id id, Inrqut01 inrqut01) {
		this.id = id;
		this.inrqut01 = inrqut01;
	}

	public Inrqpt01(Inrqpt01Id id, Inrqut01 inrqut01, String lob, String pdgrp,
			String pdsgp, String prdty, BigDecimal enhancedLiabilityValue,
			String cusdr, Long frmlocid, Long tolocid, String currcd,
			BigDecimal price, BigDecimal vat, String isDeleted,
			Serializable crtTd, Serializable updtTd) {
		this.id = id;
		this.inrqut01 = inrqut01;
		this.lob = lob;
		this.pdgrp = pdgrp;
		this.pdsgp = pdsgp;
		this.prdty = prdty;
		this.enhancedLiabilityValue = enhancedLiabilityValue;
		this.cusdr = cusdr;
		this.frmlocid = frmlocid;
		this.tolocid = tolocid;
		this.currcd = currcd;
		this.price = price;
		this.vat = vat;
		this.isDeleted = isDeleted;
		this.crtTd = crtTd;
		this.updtTd = updtTd;
	}

	public Inrqpt01Id getId() {
		return this.id;
	}

	public void setId(Inrqpt01Id id) {
		this.id = id;
	}

	public Inrqut01 getInrqut01() {
		return this.inrqut01;
	}

	public void setInrqut01(Inrqut01 inrqut01) {
		this.inrqut01 = inrqut01;
	}

	public String getLob() {
		return this.lob;
	}

	public void setLob(String lob) {
		this.lob = lob;
	}

	public String getPdgrp() {
		return this.pdgrp;
	}

	public void setPdgrp(String pdgrp) {
		this.pdgrp = pdgrp;
	}

	public String getPdsgp() {
		return this.pdsgp;
	}

	public void setPdsgp(String pdsgp) {
		this.pdsgp = pdsgp;
	}

	public String getPrdty() {
		return this.prdty;
	}

	public void setPrdty(String prdty) {
		this.prdty = prdty;
	}

	public BigDecimal getEnhancedLiabilityValue() {
		return this.enhancedLiabilityValue;
	}

	public void setEnhancedLiabilityValue(BigDecimal enhancedLiabilityValue) {
		this.enhancedLiabilityValue = enhancedLiabilityValue;
	}

	public String getCusdr() {
		return this.cusdr;
	}

	public void setCusdr(String cusdr) {
		this.cusdr = cusdr;
	}

	public Long getFrmlocid() {
		return this.frmlocid;
	}

	public void setFrmlocid(Long frmlocid) {
		this.frmlocid = frmlocid;
	}

	public Long getTolocid() {
		return this.tolocid;
	}

	public void setTolocid(Long tolocid) {
		this.tolocid = tolocid;
	}

	public String getCurrcd() {
		return this.currcd;
	}

	public void setCurrcd(String currcd) {
		this.currcd = currcd;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getVat() {
		return this.vat;
	}

	public void setVat(BigDecimal vat) {
		this.vat = vat;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Serializable getCrtTd() {
		return this.crtTd;
	}

	public void setCrtTd(Serializable crtTd) {
		this.crtTd = crtTd;
	}

	public Serializable getUpdtTd() {
		return this.updtTd;
	}

	public void setUpdtTd(Serializable updtTd) {
		this.updtTd = updtTd;
	}

}
