package com.tnt.entity;

// Generated 13 Jun, 2016 1:02:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Inrqit01Id generated by hbm2java
 */
public class Inrqit01Id implements java.io.Serializable {

	private String uuid;
	private short itmid;

	public Inrqit01Id() {
	}

	public Inrqit01Id(String uuid, short itmid) {
		this.uuid = uuid;
		this.itmid = itmid;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public short getItmid() {
		return this.itmid;
	}

	public void setItmid(short itmid) {
		this.itmid = itmid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Inrqit01Id))
			return false;
		Inrqit01Id castOther = (Inrqit01Id) other;

		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null
				&& castOther.getUuid() != null && this.getUuid().equals(
				castOther.getUuid())))
				&& (this.getItmid() == castOther.getItmid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + this.getItmid();
		return result;
	}

}
